title: "root@michaelkelnar:~"
description: "Cyber Security Engineer | Firmware Analysis | IoT Security"
url: "https://michaelkelnar.com"

# THEME SETTINGS (The Terminal Look)
remote_theme: bitbrain/jekyll-theme-terminals

# SKIN SELECTION
# Options: "ubuntu" (Orange/Purple), "arch" (Blue), "matrix" (Green), "hacker" (Green/Black)
terminals_skin: "ubuntu" 

# PROMPT SETTINGS
terminals_prompt:
  username: "michael"
  host: "kelnar"
  color: "green" # or blue, red, etc.

# PLUGINS
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# NAVIGATION (Appears as "commands" at the top)
header_pages:
  - index.md

# AUTHOR DATA
author:
  name: "Michael Kelnar"
  email: "your_email@example.com"
  github_username: "michaelk7"
  linkedin_username: "michaelkelnar"
