title: "Michael Kelnar"
lang: "en"
description: "Cyber Security Engineer | Firmware Analysis | IoT Security"
url: "https://michaelkelnar.com"

# THEME SETTINGS
remote_theme: b2a3e8/jekyll-theme-console

# STYLE: Choose 'hacker' (Green), 'dark' (Modern), or 'nord' (Blueish)
style: hacker

# PLUGINS
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag

# MENU (Top Right)
header_pages:
  - index.md

# FOOTER
footer: 'root@kelnar:~/portfolio# <a href="https://linkedin.com/in/michael-kelnar">LinkedIn</a> | <a href="https://github.com/michaelk7">GitHub</a>'
